--- #YAML:1.0
name:               WWW-NOS-Open
version:            0.02
abstract:           Perl framework for the
author:
    - Roland van Ipenburg <ipenburg@xs4all.nl>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:        0.81
    Test::NoWarnings:  0
requires:
    Date::Calc:           0
    Date::Format:         0
    Date::Parse:          0
    DateTime:             0
    Exception::Class:     0
    HTTP::Headers:        0
    HTTP::Request:        0
    HTTP::Status:         0
    JSON:                 0
    Log::Log4perl:        0
    LWP::UserAgent:       0
    Moose:                0
    Moose::Role:          0
    Moose::Util::TypeConstraints:  0
    MooseX::Types:        0
    MooseX::Types::Moose:  0
    namespace::autoclean:  0
    Readonly:             0
    URI:                  0
    URI::Escape:          0
    XML::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
